config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div id="footer">
<div class="container">
    <div class="row">

    <!-- Tweets -->
        <section class="col-4 col-12-mobile">
        <header>
            <h2 class="icon brands fa-twitter circled"><span class="label">Tweets</span></h2>
        </header>
        <ul class="divided">
            <li>
            <article class="tweet">
                Amet nullam fringilla nibh nulla convallis tique ante sociis accumsan.
                <span class="timestamp">5 minutes ago</span>
            </article>
            </li>
            <li>
            <article class="tweet">
                Hendrerit rutrum quisque.
                <span class="timestamp">30 minutes ago</span>
            </article>
            </li>
            <li>
            <article class="tweet">
                Curabitur donec nulla massa laoreet nibh. Lorem praesent montes.
                <span class="timestamp">3 hours ago</span>
            </article>
            </li>
            <li>
            <article class="tweet">
                Lacus natoque cras rhoncus curae dignissim ultricies. Convallis orci aliquet.
                <span class="timestamp">5 hours ago</span>
            </article>
            </li>
        </ul>
        </section>

    <!-- Posts -->
        <section class="col-4 col-12-mobile">
        <header>
            <h2 class="icon solid fa-file circled"><span class="label">Posts</span></h2>
        </header>
        <ul class="divided">
            <li>
            <article class="post stub">
                <header>
                <h3><a href="#">Nisl fermentum integer</a></h3>
                </header>
                <span class="timestamp">3 hours ago</span>
            </article>
            </li>
            <li>
            <article class="post stub">
                <header>
                <h3><a href="#">Phasellus portitor lorem</a></h3>
                </header>
                <span class="timestamp">6 hours ago</span>
            </article>
            </li>
            <li>
            <article class="post stub">
                <header>
                <h3><a href="#">Magna tempus consequat</a></h3>
                </header>
                <span class="timestamp">Yesterday</span>
            </article>
            </li>
            <li>
            <article class="post stub">
                <header>
                <h3><a href="#">Feugiat lorem ipsum</a></h3>
                </header>
                <span class="timestamp">2 days ago</span>
            </article>
            </li>
        </ul>
        </section>

    <!-- Photos -->
        <section class="col-4 col-12-mobile">
        <header>
            <h2 class="icon solid fa-camera circled"><span class="label">Photos</span></h2>
        </header>
        <div class="row gtr-25">
            <div class="col-6">
            <a href="#" class="image fit"><img src="images/pic10.jpg" alt="" /></a>
            </div>
            <div class="col-6">
            <a href="#" class="image fit"><img src="images/pic11.jpg" alt="" /></a>
            </div>
            <div class="col-6">
            <a href="#" class="image fit"><img src="images/pic12.jpg" alt="" /></a>
            </div>
            <div class="col-6">
            <a href="#" class="image fit"><img src="images/pic13.jpg" alt="" /></a>
            </div>
            <div class="col-6">
            <a href="#" class="image fit"><img src="images/pic14.jpg" alt="" /></a>
            </div>
            <div class="col-6">
            <a href="#" class="image fit"><img src="images/pic15.jpg" alt="" /></a>
            </div>
        </div>
        </section>

    </div>
    <hr />
    <div class="row">
    <div class="col-12">

        <!-- Contact -->
        <section class="contact">
            <header>
            <h3>Nisl turpis nascetur interdum?</h3>
            </header>
            <p>Urna nisl non quis interdum mus ornare ridiculus egestas ridiculus lobortis vivamus tempor aliquet.</p>
            <ul class="icons">
            <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
            <li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
            <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">Linkedin</span></a></li>
            </ul>
        </section>

        <!-- Copyright -->
        <div class="copyright">
            <ul class="menu">
            <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>

    </div>

    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <div id="page-wrapper">

  <!-- Header -->
    <div id="header">

      <!-- Inner -->
        <div class="inner">
          <header>
            <h1><a href="index.html" id="logo">Helios</a></h1>
            <hr />
            <p>Another fine freebie by HTML5 UP</p>
          </header>
          <footer>
            <a href="#banner" class="button circled scrolly">Start</a>
          </footer>
        </div>

      <!-- Nav -->
        <nav id="nav">
          <ul>
            <li><%= link_to "One", pages_one_path %></li>
            <li><%= link_to "Two", pages_two_path %></li>
            <li><%= link_to "Three", pages_three_path %></li>
          </ul>
        </nav>

    </div>

  <!-- Banner -->
    <section id="banner">
      <header>
        <h2>Hi. You re looking at <strong>Helios</strong>.</h2>
        <p>
          A (free) responsive site template by <a href="http://html5up.net">HTML5 UP</a>.
          Built with HTML5/CSS3 and released under the <a href="http://html5up.net/license">CCA</a> license.
        </p>
      </header>
    </section>

  <!-- Carousel -->
    <section class="carousel">
      <div class="reel">

        <article>
          <a href="#" class="image featured"><%= image_tag "pic01.jpg" %></a>
          <header>
            <h3><a href="#">Pulvinar sagittis congue</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic02.jpg" %></a>
          <header>
            <h3><a href="#">Fermentum sagittis proin</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic03.jpg" %></a>
          <header>
            <h3><a href="#">Sed quis rhoncus placerat</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic04.jpg" %></a>
          <header>
            <h3><a href="#">Ultrices urna sit lobortis</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic05.jpg" %></a>
          <header>
            <h3><a href="#">Varius magnis sollicitudin</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic01.jpg" %></a>
          <header>
            <h3><a href="#">Pulvinar sagittis congue</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic02.jpg" %></a>
          <header>
            <h3><a href="#">Fermentum sagittis proin</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic03.jpg" %></a>
          <header>
            <h3><a href="#">Sed quis rhoncus placerat</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic04.jpg" %></a>
          <header>
            <h3><a href="#">Ultrices urna sit lobortis</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

        <article>
          <a href="#" class="image featured"><%= image_tag "pic05.jpg" %></a>
          <header>
            <h3><a href="#">Varius magnis sollicitudin</a></h3>
          </header>
          <p>Commodo id natoque malesuada sollicitudin elit suscipit magna.</p>
        </article>

      </div>
    </section>

  <!-- Main -->
    <div class="wrapper style2">

      <article id="main" class="container special">
        <a href="#" class="image featured"><img src="images/pic06.jpg" alt="" /></a>
        <header>
          <h2><a href="#">Sed massa imperdiet magnis</a></h2>
          <p>
            Sociis aenean eu aenean mollis mollis facilisis primis ornare penatibus aenean. Cursus ac enim
            pulvinar curabitur morbi convallis. Lectus malesuada sed fermentum dolore amet.
          </p>
        </header>
        <p>
          Commodo id natoque malesuada sollicitudin elit suscipit. Curae suspendisse mauris posuere accumsan massa
          posuere lacus convallis tellus interdum. Amet nullam fringilla nibh nulla convallis ut venenatis purus
          sit arcu sociis. Nunc fermentum adipiscing tempor cursus nascetur adipiscing adipiscing. Primis aliquam
          mus lacinia lobortis phasellus suscipit. Fermentum lobortis non tristique ante proin sociis accumsan
          lobortis. Auctor etiam porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum
          consequat integer interdum integer purus sapien. Nibh eleifend nulla nascetur pharetra commodo mi augue
          interdum tellus. Ornare cursus augue feugiat sodales velit lorem. Semper elementum ullamcorper lacinia
          natoque aenean scelerisque.
        </p>
        <footer>
          <a href="#" class="button">Continue Reading</a>
        </footer>
      </article>

    </div>

  <!-- Features -->
    <div class="wrapper style1">

      <section id="features" class="container special">
        <header>
          <h2>Morbi ullamcorper et varius leo lacus</h2>
          <p>Ipsum volutpat consectetur orci metus consequat imperdiet duis integer semper magna.</p>
        </header>
        <div class="row">
          <article class="col-4 col-12-mobile special">
            <a href="#" class="image featured"><img src="images/pic07.jpg" alt="" /></a>
            <header>
              <h3><a href="#">Gravida aliquam penatibus</a></h3>
            </header>
            <p>
              Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
              porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
            </p>
          </article>
          <article class="col-4 col-12-mobile special">
            <a href="#" class="image featured"><img src="images/pic08.jpg" alt="" /></a>
            <header>
              <h3><a href="#">Sed quis rhoncus placerat</a></h3>
            </header>
            <p>
              Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
              porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
            </p>
          </article>
          <article class="col-4 col-12-mobile special">
            <a href="#" class="image featured"><img src="images/pic09.jpg" alt="" /></a>
            <header>
              <h3><a href="#">Magna laoreet et aliquam</a></h3>
            </header>
            <p>
              Amet nullam fringilla nibh nulla convallis tique ante proin sociis accumsan lobortis. Auctor etiam
              porttitor phasellus tempus cubilia ultrices tempor sagittis. Nisl fermentum consequat integer interdum.
            </p>
          </article>
        </div>
      </section>

    </div>
  <!-- Footer -->
  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>

  </body>
</html>

app/views/pages/one.html.erb
<h1>Humberto Ferreira Yañez</h1>
<p>Find me in app/views/pages/one.html.erb</p>

<%= image_tag 'rutas.png' %>

app/views/pages/three.html.erb
<h2> Esta es la pagina Trhee </h2>
<p> dsaddasdadasdakjidajkdoadio iajd oiasjdiojas djasioj daiosj iodasjdo aksdio jasio asd njandklajdk lasnd akbndklajsn dkjl</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>